"""Type stubs for the native ``rsmf._rsmf`` extension module."""

from __future__ import annotations

from typing import Any

import numpy as np

from ._types import FileInfo, TensorInfo, VariantInfo

class RsmfFile:
    def __init__(self, path: str) -> None: ...
    def __repr__(self) -> str: ...
    def tensor_names(self) -> list[str]: ...
    def asset_names(self) -> list[str]: ...
    def graph_count(self) -> int: ...
    def graph_kind(self, idx: int) -> str: ...
    def get_graph(self, idx: int) -> bytes: ...
    def metadata(self) -> dict[str, str]: ...
    def file_info(self) -> FileInfo: ...
    def tensor_info(self, name: str) -> TensorInfo: ...
    def verify(self) -> None: ...
    def get_tensor(
        self,
        name: str,
        target: str | None = ...,
        strict: bool = ...,
    ) -> np.ndarray[Any, Any]: ...
    def tensor_variants(self, name: str) -> list[VariantInfo]: ...
    def get_tensor_variant(
        self, name: str, variant_idx: int
    ) -> np.ndarray[Any, Any]: ...
    def get_asset(self, name: str) -> bytes | None: ...

class RsmfError(Exception): ...
class RsmfNotFound(RsmfError): ...
class RsmfStructuralError(RsmfError): ...
class RsmfVerificationError(RsmfError): ...
class RsmfIoError(RsmfError): ...
class RsmfUnsupportedError(RsmfError): ...
